# Generated by Django 5.2.6 on 2025-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
